name: "CI/CD Pipeline"

on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/**"
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: "Lambda Functions (Linting)"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: "[Authorizer Lambda Function] Install Dependencies & Run Linters"
        working-directory: terraform/authorizer
        run: |
          npm ci
          npx eslint function.js

      - name: "[Hello Lambda Function] Install Dependencies & Run Linters"
        working-directory: terraform/hello
        run: |
          npm ci
          npx eslint function.js

      - name: "[Goodbye Lambda Function] Install Dependencies & Run Linters"
        working-directory: terraform/goodbye
        run: |
          npm ci
          npx eslint function.js

      - name: "[Welcome Lambda Function] Install Dependencies & Run Linters"
        working-directory: terraform/welcome
        run: |
          npm ci
          npx eslint function.js

  unit_tests:
    name: "Lambda Functions (Unit Testing)"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: "[Authorizer Lambda Function] Install Dependencies & Run Tests"
        working-directory: terraform/authorizer
        run: |
          npm ci
          npm run test tests/

      - name: "[Hello Lambda Function] Install Dependencies & Run Tests"
        working-directory: terraform/hello
        run: |
          npm ci
          npm run test tests/

      - name: "[Goodbye Lambda Function] Install Dependencies & Run Tests"
        working-directory: terraform/goodbye
        run: |
          npm ci
          npm run test tests/

      - name: "[Welcome Lambda Function] Install Dependencies & Run Tests"
        working-directory: terraform/welcome
        run: |
          npm ci
          npm run test tests/

  deployment:
    needs: [linting, unit_tests]
    if: "${{ contains(github.event.head_commit.message, '[deploy]') }}"
    name: "Deploy (Terraform -> AWS)"
    runs-on: ubuntu-latest
    outputs:
      api_base_url: ${{steps.options.outputs.api_base_url}}
      api_key_free_plan: ${{steps.options.outputs.api_key_free_plan}}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: terraform
        run: terraform apply -auto-approve -input=false

      - name: Set Step's Output with `api_base_url_production` value from <terraform output>
        id: api_base_url_step
        working-directory: terraform
        run: |
          api_base_url=$(terraform output -raw api_base_url_production)
          echo $api_base_url
          echo "::set-output name=value::${api_base_url}"

      - name: Set Step's Output with `api_key_free_plan` value from <terraform output>
        id: api_key_free_plan_step
        working-directory: terraform
        run: |
          api_key_free_plan=$(terraform output -raw api_key_free_plan)
          echo $api_key_free_plan
          echo "::set-output name=value::${api_key_free_plan}"

      - name: Set Job's Output with `api_base_url` & `api_key_free_plan` values
        uses: actions/github-script@v5
        id: options
        with:
          script: |
            console.log('*** api_base_url:', '${{steps.api_base_url_step.outputs.value}}');
            console.log('*** api_key_free_plan:', '${{steps.api_key_free_plan_step.outputs.value}}');
            core.setOutput('api_base_url', '${{steps.api_base_url_step.outputs.value}}');
            core.setOutput('api_key_free_plan', '${{steps.api_key_free_plan_step.outputs.value}}');

  integration_tests:
    needs: deployment
    name: "API Testing (Integration)"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Hello Endpoint
        working-directory: terraform/hello/tests
        run: |
          api_base_url="${{ needs.deployment.outputs.api_base_url }}"
          echo $api_base_url
          bash integration.test.sh $api_base_url

      - name: Goodbye Endpoint
        working-directory: terraform/goodbye/tests
        run: |
          api_base_url="${{ needs.deployment.outputs.api_base_url }}"
          echo $api_base_url
          bash integration.test.sh $api_base_url

      - name: Welcome Endpoint
        working-directory: terraform/welcome/tests
        run: |
          api_base_url="${{ needs.deployment.outputs.api_base_url }}"
          api_key_free_plan="${{ needs.deployment.outputs.api_key_free_plan }}"
          echo $api_base_url
          echo $api_key_free_plan
          bash integration.test.sh $api_base_url $api_key_free_plan

  load_tests:
    needs: [deployment, integration_tests]
    name: "API Testing (Load)"
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make reports directory
        run: mkdir reports

      - name: Execute load tests for `hello` endpoint
        env:
          TARGET: "${{ needs.deployment.outputs.api_base_url }}"
        run: /home/node/artillery/bin/run run --output reports/load_test_report_hello_endpoint.json terraform/hello/tests/load_test.yaml

      - name: Generate HTML report for `hello` endpoint
        run: /home/node/artillery/bin/run report --output reports/load_test_report_hello_endpoint.html reports/load_test_report_hello_endpoint.json

      # - name: Execute load tests for `goodbye` endpoint
      #   env:
      #     TARGET: "${{ needs.deployment.outputs.api_base_url }}"
      #   run: /home/node/artillery/bin/run run --output reports/load_test_report_goodbye_endpoint.json terraform/goodbye/tests/load_test.yaml

      # - name: Generate HTML report for `goodbye` endpoint
      #   run: /home/node/artillery/bin/run report --output reports/load_test_report_goodbye_endpoint.html reports/load_test_report_goodbye_endpoint.json

      # - name: Execute load tests for `welcome` endpoint
      #   env:
      #     TARGET: "${{ needs.deployment.outputs.api_base_url }}"
      #     FREE_API_KEY: "${{ needs.deployment.outputs.api_key_free_plan }}"
      #   run: /home/node/artillery/bin/run run --output reports/load_test_report_welcome_endpoint.json terraform/welcome/tests/load_test.yaml

      # - name: Generate HTML report for `welcome` endpoint
      #   run: /home/node/artillery/bin/run report --output reports/load_test_report_welcome_endpoint.html reports/load_test_report_welcome_endpoint.json

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: artillery-test-report
          path: reports/*

  #     -> Validate API Key usage (implement - TODO)
  #     -> Rate limit API Key users to 10 requests per second

  # send-notification:
  #   runs-on: [ubuntu-latest]
  #   timeout-minutes: 7200
  #   needs: [linting, unit_tests, deployment, integration_tests, load_tests]
  #   if: ${{ always() }}
  #   steps:
  #     - name: Send Slack Notification
  #       uses: rtCamp/action-slack-notify@v2
  #       if: always()
  #       env:
  #         SLACK_CHANNEL: devops-sample-slack-channel
  #         SLACK_COLOR: ${{ job.status }}
  #         SLACK_ICON: https://avatars.githubusercontent.com/u/54465427?v=4
  #         SLACK_MESSAGE: |
  #           "Lambda Functions (Linting): ${{ needs.linting.outputs.status || 'Not Performed' }}" \
  #           "Lambda Functions (Unit Testing): ${{ needs.unit_tests.outputs.status || 'Not Performed' }}" \
  #           "API Deployment: ${{ needs.deployment.outputs.status }}" \
  #           "API Tests (Integration): ${{ needs.integration_tests.outputs.status || 'Not Performed' }}" \
  #           "API Tests (Load): ${{ needs.load_tests.outputs.status || 'Not Performed' }}"
  #         SLACK_TITLE: CI/CD Pipeline Results
  #         SLACK_USERNAME: Github Actions Bot
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
